# Site settings
title: "CMS.636/855"
full_name: "CMS.636/855 – Extending the Museum"
name: "Extending the Museum"
email: fendt@mit.edu
description: > # this means to ignore newlines until "baseurl:"
  This is the collaborative site for CMS.636/855 - Extending the Museum, a Digital
  Humanities course at MIT taught by Kurt Fendt. Students will
  use this space to keep track of course resources and example
  projects, as well as to post updates as their own design
  projects take shape.
baseurl: "/Fall-2020" # the subpath of your site, e.g. /blog/
url: "http://cms636.github.io/Fall-2020/" # the base hostname & protocol for your site
twitter_username: activearchives
github_username: cms636
permalink: none

# Build settings
markdown: kramdown

prose:
  rooturl: '_posts'
  siteurl: "http://cms636.github.io/Fall-2020/"
  relativeLinks: 'http://cms636.github.io/Fall-2020/links.jsonp'
  media: 'assets'
  metadata:
    _posts:
      - name: "published"
        field:
          element: "checkbox"
          label: "Publish"
      - name: "author"
        field:
          element: "text"
          label: "Author"
          placeholder: "your name, or your team's name"
      - name: "category"
        field:
          element: "select"
          label: "Category"
          options:
            - name: "Project Update"
              value: "updates"
            - name: "Reading Commentary"
              value: "commentary"
            - name: "Bio"
              value: "people"
            - name: "Museum Projects"
              value: "ext-projects"
            - name: "Data Sets"
              value: "datasets"
            - name: "About"
              value: "course"
      - name: "tags"
        field:
          element: "multiselect"
          label: "Readings"
          placeholder: "Choose Reading(s)"
          options:
            - name: "Digital_Humanities"
              value: "Digital_Humanities"
            - name: "Cartographies of Time"
              value: "Cartographies of Time"
            - name: "Spatial Humanities"
              value: "Spatial Humanities"
            - name: "The Database"
              value: "The Database"
            - name: "Museum"
              value: "Museum"
            - name: "Augmented Space"
              value: "Augmented Space"
            - name: "Sonification"
              value: "Sonification"
            - name: "Participatory Culture"
              value: "Participatory Culture"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "layout"
        field:
          element: "hidden"
          value: "post"

    _posts/static:
      - name: "layout"
        field:
          element: "hidden"
          value: "page"
      - name: "title"
        field:
          element: "text"
          label: "Title"
          value: ""
      - name: "permalink"
        field:
          element: "text"
          label: "Permalink"
          value: ""
